name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: 'ubuntu-latest'
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: ['1.6', '^1']
        experimental: [false]
        arch:
          - x64
        include:
          - version: 'nightly'
            experimental: true
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - run: julia --color=yes --project=. -e 'if VERSION < v"1.9"; using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); end'
        working-directory: ${{ github.workspace }}
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
